apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-healthcheck
  namespace: payload-app
  labels:
    app: app-healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-healthcheck
  template:
    metadata:
      labels:
        app: app-healthcheck
    spec:
      containers:
      - name: app-healthcheck
        image: registry.spacefx.local:5000/app-healthcheck:0.11.0-nightly
        args: ["/workspace/app-healthcheck/app-healthcheck.dll"]
        imagePullPolicy: IfNotPresent
        command: ["dotnet"]
        workingDir: "/workspace/app-healthcheck"
        env:
        - name: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
          value: "1"